submission
Data-Epic/Omotosho_Ayomide pull request #1
Opened 2023-10-16 20:59 UTC by LogicAL007

2023-10-16 22:47 UTC, elseagle requested changes
Goof start @LogicAL007 - added some comments.

Kindly use descriptive titles for your PRs and commits. Also, could you add description so we can have a summary of what you've built? 

A readme markdown file to give detail insight to your project

2023-10-16 22:47 UTC, elseagle commented on my_gspread.py
> +# worksheet= spreadsheet.worksheet("Ecommerce store")
remove redundant comments

2023-10-16 22:47 UTC, elseagle commented on omotosho-project-c92e4f4bc071.json
> +{
don't commit a credential file. Use .env with `decouple` or `python-dotenv` library. Ensure you add your .env to .gitignore

2023-10-16 22:47 UTC, elseagle commented on my_gspread.py
> +def get_or_create_worksheet(spreadsheet, Ecom , rows=1, cols=1):
add docstring to explain what your code does

2023-10-16 22:47 UTC, elseagle commented on my_gspread.py
> +def populate_worksheet(Ecom):
some docstring or comment will help here

2023-10-16 22:47 UTC, elseagle commented on my_gspread.py
> +print(worksheet_list)
don't use print, checkout the `logging` library and replace all print statements with it

2023-10-18 08:32 UTC, elseagle commented on my_gspread.py
> +def get_or_create_worksheet(spreadsheet, Ecom , rows=1, cols=1):
don't use title format for parameters "Ecom" should be "ecom"

2023-10-18 08:34 UTC, elseagle commented on my_gspread.py
> +    worksheet = get_or_create_worksheet(spreadsheet, Ecom, rows=df.shape[0]+1, cols=df.shape[1])
can you comment on this line to help us know why you are doing `df.shape[0]+1` ? It is unclear to everyone else except , help us make it clear to anyone that picks your code

2023-10-20 02:40 UTC, tobaadesugba requested changes

2023-10-20 02:40 UTC, tobaadesugba commented on README.md
> -# Populating an excel sheet with Gspread library
Your readme is a little incomplete. Include details like the author of the project, the tools you used, the source of the data used, and other details you feel are important.

2023-10-22 14:18 UTC, elseagle approved these changes

2023-10-24 16:17 UTC, merged